### ISSUE TITLE
Vertical/horizontal layouts

### ISSUE THREAD

**Issue by kurdtpage** [lightful/xfce-hkmon#5]
Would be good to have options for horizontal or vertical layouts. I find it works really well when added to a blank panel using vertical layout, but would be good to have it added to a horizontal panel that's small (like 32 pixels tall)

**Comment by lightful** [comment]
I personally use horizontal panels, albeit a bit wide...
I have added a **LINE** option to place all the output in the panel in a single line.
In addition, if the CPU is not selected, TEMP now doesn't appears in the panel either.
If the CPU is selected, not only TEMP, but also RAM instead may now appear by his side (the one first listed in the parameters).
